CREATE DATABASE IF NOT EXISTS codelearn_db;

USE codelearn_db;

CREATE TABLE IF NOT EXISTS feedback_app_feedback (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  message TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
